language: cpp
sudo: false

matrix:
  include:

    #==============================
    #
    #          osx gcc
    #
    #==============================

    - os: osx
      osx_image: xcode11.4
      compiler: gcc-4.9
      env: MATRIX_EVAL="brew install gcc@4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode11.4
      compiler: gcc-5
      env: MATRIX_EVAL="brew install gcc@5 && CXX=g++-5"

    - os: osx
      osx_image: xcode11.4
      compiler: gcc-6
      env: MATRIX_EVAL="brew install gcc@6 && CXX=g++-6"

    - os: osx
      osx_image: xcode11.4
      compiler: gcc-7
      env: MATRIX_EVAL="brew install gcc@7 && CXX=g++-7"

    - os: osx
      osx_image: xcode11.4
      compiler: gcc-8
      env: MATRIX_EVAL="brew install gcc@8 && CXX=g++-8"

    #==============================
    #
    #          osx clang
    #
    #==============================

    - os: osx
      osx_image: xcode8.3
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode9.2
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode9.4
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode10.1
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode10.2
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode10.3
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode11
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode11.1
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode11.2
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode11.3
      env: MATRIX_EVAL="CXX=clang++"

    - os: osx
      osx_image: xcode11.4
      env: MATRIX_EVAL="CXX=clang++"

    #==============================
    #
    #          linux gcc 
    #
    #==============================

    - os: linux
      dist: xenial
      compiler: gcc-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env: MATRIX_EVAL="CXX=g++-4.8"
      
    - os: linux
      dist: xenial
      compiler: gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: MATRIX_EVAL="CXX=g++-4.9"
      
    - os: linux
      dist: xenial
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: MATRIX_EVAL="CXX=g++-5"
      
    - os: linux
      dist: xenial
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: MATRIX_EVAL="CXX=g++-6"
      
    - os: linux
      dist: xenial
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="CXX=g++-7"
      
    - os: linux
      dist: xenial
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: MATRIX_EVAL="CXX=g++-8"
      
    - os: linux
      dist: xenial
      compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: MATRIX_EVAL="CXX=g++-9"

    #==============================
    #
    #          linux clang 
    #
    #==============================

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CXX=clang++-3.6"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CXX=clang++-4.0"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CXX=clang++-6.0"

before_install:
  - eval ${MATRIX_EVAL}

before_script:
  - cd ${TRAVIS_BUILD_DIR}/..  
  - mkdir build_debug
  - mkdir build_release

script:
  - cd build_debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${CXX} ${TRAVIS_BUILD_DIR} 
  - cmake --build .
  - cd ../build_release
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${CXX} ${TRAVIS_BUILD_DIR} 
  - cmake --build .